services:
  app:
    image: php:8.2-cli
    container_name: php-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
